name: Publish NuGet Package

on:
  push:
    branches:
      - main
      - release/*
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.802
      - name: Test the package
        run: dotnet test
      - name: Publish the package
        run: |
          dotnet pack -o out --configuration Release
          cp ./.github/workflows/nuget.config ./
          dotnet nuget push SierraLib.API.Views/out/*.nupkg -s GitHub
          dotnet nuget push SierraLib.API.Views/out/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
